name: Check Dependencies' License

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Graphviz (required to compile for now)
        uses: ts-graphviz/setup-graphviz@v1
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
         distribution: temurin
         java-version: '21'
      - name: List dependencies (resolve)
        uses: apache/skywalking-eyes/dependency@main
        with:
          log: debug
          mode: resolve
          config: ${{ github.workspace }}/.licenserc.yaml
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@main
        with:
          log: debug
          config: ${{ github.workspace }}/.licenserc.yaml
